### ISSUE TITLE
Feature request: Support error analysis in Jupyter Lab

### ISSUE THREAD

**Issue by AvneeshSarwate** [Kotlin/kotlin-jupyter#395] opened 2023-02-06 18:21 UTC
E.g, support this functionalty https://github.com/Kotlin/kotlin-jupyter#error-analysis from Notebook in Lab

**Comment by ileasile** [comment] 2023-02-18 05:37
Hi! It's a duplicate of https://github.com/Kotlin/kotlin-jupyter/issues/188
See also related discussions in Kotlin Slack

**Closed by ileasile** 2023-02-18 05:37 UTC
