### ISSUE TITLE
Can kotlin-jupyter be run on IntelliJ IDEA?

### ISSUE THREAD

**Issue by takahirom** [Kotlin/kotlin-jupyter#122] opened 2021-01-28 00:46 UTC
# Environment
Build #IU-203.6682.115, built on December 23, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
Non-Bundled Plugins: IdeaVIM, org.jetbrains.kotlin, Pythonid, com.jetbrains.edu

When run on IntelliJ IDEA
![image](https://user-images.githubusercontent.com/1386930/106073403-59afc680-614d-11eb-8fb0-29ec06444ae9.png)

**Comment by altavir** [comment] 2021-01-28 13:00
Not yet, they are working on it.

**Comment by Jolanrensen** [comment] 2021-04-23 13:50
You can see the progress here: https://plugins.jetbrains.com/plugin/16340-kotlin-notebook
Unfortunately the plugin requires IntelliJ 2021.2 which is (as of writing) not released yet.

**Comment by breandan** [comment] 2021-05-30 03:35
Since `2021.2 EAP` was recently [released](https://blog.jetbrains.com/idea/2021/05/intellij-idea-2021-2-eap-1/), after installing the above plugin I can confirm that Jupyter notebook is supported with IntelliJ IDEA, although completion and static analysis does not appear to work at the moment. cc: @agbragin

![Screenshot from 2021-05-29 23-20-48](https://user-images.githubusercontent.com/175716/120090983-c5db1080-c0d4-11eb-9b76-f522001d6b44.png)

**Comment by ileasile** [comment] 2021-05-30 04:09
@breandan I believe that for achieving the above result you don't even need to install the plugin.
This plugin is not in a usable state yet, because of the need for custom Kotlin scripting support for notebooks, and its implementation is blocked with the following issues for now:
https://youtrack.jetbrains.com/issue/IDEA-266381
https://youtrack.jetbrains.com/issue/DS-1712

Please don't use this plugin for now, I will mention it here once the first real release will be delivered.

**Comment by Jolanrensen** [comment] 2021-11-30 18:14
I see the plugin has come a long way and can actually run in 2021.3! 
I do still get errors (probably because it's not yet finished) like:
`Cannot access script base class 'jupyter.kotlin.ScriptTemplateWithDisplayHelpers'. Check your module classpath for missing or conflicting dependencies`
But continue the good work :D

**Comment by Stvad** [comment] 2022-04-11 21:51
It's really weird: when I create a new kotlin project and set a Python facet in it, then create the kotlin jupyter notebook there - autocompletion works in it for a while (at least for standard language constructs if not DataFrame imported though `%use` magic). 

- If I were to close  the notebook after working with it for a bit - sometimes I can't open it anymore (clicking/selecting it from action menu just does nothing)
- restarting IDE does not help
- making a copy of the notebook and opening that works, but autocompletion stops working

**Comment by ileasile** [comment] 2022-04-11 22:58
@Stvad Could you please file an issue in https://youtrack.jetbrains.com/issues/KTNB?
Exceptions reports and IDEA logs would be very helpful

**Comment by ucasqsl** [comment] 2022-05-19 12:19
> I do still get errors (probably because it's not yet finished) like:
> `Cannot access script base class 'jupyter.kotlin.ScriptTemplateWithDisplayHelpers'. Check your module classpath for missing or conflicting dependencies`

Encounter this problem too with 2022.1, any suggestions on how to solve this problem?

**Comment by nort3x** [comment] 2022-08-07 14:35
any updates?

**Comment by ileasile** [comment] 2022-09-26 12:55
@qseworks @nort3x You can try the latest (EAP) versions:
https://plugins.jetbrains.com/plugin/16340-kotlin-notebook/versions/stable
It doesn't require Python SDK anymore (however still requires Python plugin) and should have better performance.

Please file the issues you have here: https://youtrack.jetbrains.com/issues/KTNB.
I'll close this issue.

**Closed by ileasile** 2022-09-26 12:55 UTC
Labels: feature
