### ISSUE TITLE
Internal error for if expression

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kotlin-jupyter#47] opened 2020-02-18 15:44 UTC
When executing the following code:
```
fun test() {
    if() {    }
}
```
error:
```
Back-end (JVM) Internal error: Failed to generate expression: KtIfExpression
File being compiled: (2,5) in Line_1.jupyter.kts
The root cause java.lang.IllegalArgumentException was thrown at: org.jetbrains.kotlin.codegen.ExpressionCodegen.$$$reportNull$$$0(ExpressionCodegen.java)
```

I expect compilation error in readable form.

**Comment by ileasile** [comment] 2020-04-21 01:07
Should be fixed in the latest version **0.7.41.254.dev1**, please check
![image](https://user-images.githubusercontent.com/20319593/79813851-74b30600-8385-11ea-8355-a101eeac7286.png)

**Comment by devcrocod** [comment] 2020-04-21 09:24
It works, thanks.

It also works with `when`. But doesn't emphasize where the error is, is it normal?
![image](https://user-images.githubusercontent.com/19648120/79849318-f8431600-83ca-11ea-8092-1b9101cf4052.png)

**Comment by ileasile** [comment] 2020-04-21 17:32
Cannot reproduce it. For me error is emphasized. Recheck it please for version `0.7.41.255.dev8`

**Comment by devcrocod** [comment] 2020-04-21 18:07
I found that this does not work in jupyter-lab. Now `if` and` when` are not underlined on error for version 0.7.41.255.dev8.
In jupyter-notebook it works correctly.

**Comment by ileasile** [comment] 2020-04-21 18:20
It should not work in Lab, because JS extension is only applicable to jupyter-notebook frontend. Error messages are sent, but not rendered. Same thing for completion: it works only for  Tab, not on type.

**Comment by ileasile** [comment] 2020-04-21 18:21
So, if it's ok in Notebook, I will close the issue

**Closed by ileasile** 2020-04-21 18:21 UTC
Labels: wait for answer
